# Taps
tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'beeftornado/rmtree'

# Install Binaries
brew 'cmake'
brew 'curl', args: ["with-openssl"], link: true, force: true
brew 'git'
brew 'htop'
brew 'mackup'
brew 'nmap'
brew 'openssh'
brew 'openssl'
brew 'python'
brew 'ssh-copy-id'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# Development
brew 'sbt'
brew 'scala'
brew 'apache-spark'

# Apps
cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'appcleaner'
cask 'chromium'
cask 'docker'
cask 'dropbox'
cask 'easyfind'
cask 'firefox'
cask 'google-chrome'
cask 'istat-menus5'
cask 'iterm2'
cask 'java8'
cask 'little-snitch'
cask 'macdown'
cask 'mactex'
cask 'miniconda'
cask 'skype'
cask 'spectacle'
cask 'sublime-text'
cask 'telegram'
cask 'torbrowser'
cask 'transmission'
cask 'tunnelblick'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'

